### ISSUE TITLE
Detrending ROIs?

### ISSUE THREAD

**Issue by hummuscience** [rorynolan/detrendr#4]
Is it possible to use the package to detrend single ROIs (traces) instead of a whole movie?

I basically just have a matrix with each ROI being a column and rows being frames.

**Comment by rorynolan** [comment]
Hi @Cumol 
I think this is possible but I'll need a bit more info. Were these traces acquired simultaneously or sequentially? (In _simultaneously_ I mean all of the first time-points from all of the ROIs were acquired, followed by all of the second time-points and so on)? If you're in the simultaneous case, you can use my package no problem and I'll show you how.
Let me know and if it can work, I'll send you the code to do what you need.
Rory

**Comment by hummuscience** [comment]
Yes, they were all acquired simultaneously. Each ROI represents a single cell in a time course calcium imaging experiment.

**Comment by rorynolan** [comment]
Ok then the approach is basically outlined in https://cran.r-project.org/web/packages/detrendr/vignettes/linescan-data.html. Let me know if that helps you. Otherwise, you can send me your data and I'll send you back the code to do what you want.

**Comment by hummuscience** [comment]
I stumbled onto this but did not exactly know if this will work.

First, it seems like I need to construct an `ijtiff_img` object, right?

Second, I am not sure how to do that with my data. For example, lets say I have 10 ROIs and 2000 frames (timepoints). There are two options that I can think of. 10 ijtiff_img object with the following structure:

`#> [1]    1   1    1 2000`

Or one ijtiff_img object with the following structure:

`#> [1]    1   10    1 2000`

Does detrendr calculate the decay along each individual pixel (in my case, the average intensity of a ROI), independent of the others? From what I understand now, it is not the case, but maybe I am misjudging it.

I attached a dummy dataset from me. Each column is a ROI. Each row is a timepoint/frame. The values are average intensity values over that ROI in time. My intention is to detrend every column separately. You will notice that some of them show a stronger decay than others (they also have different base mean fluorescence).

It should be easily readable with `df <- read.csv()` and standard arguments.

[dummy.txt](https://github.com/rorynolan/detrendr/files/4807491/dummy.txt)

Btw, I am currently writing a package to analyze calcium imaging data (after extraction of ROIs) and I hope that your methods can find a place in it :)

**Comment by rorynolan** [comment]
Hi @Cumol 
Here's a script showing how to detrend your traces using detrendr. 

``` r
library(magrittr)
library(ijtiff)
library(detrendr)

# read
traces <- read.csv("~/Downloads/dummy.txt")
dim(traces)
#> [1] 4045   85

# transform for detrendr
traces_transformed <- traces %>% 
  as.matrix() %>% 
  ijtiff_img() %>% 
  linescan_to_stack()
dim(traces_transformed)
#> [1]    1   85    1 4045

# detrend
traces_transformed_detrended <- img_detrend_exp(traces_transformed, 
                                                tau = 100, purpose = "FCS")
dim(traces_transformed_detrended)
#> [1]    1   85    1 4045

# transform back
traces_detrended <- stack_to_linescan(traces_transformed_detrended)
dim(traces_detrended)
#> [1] 4045   85    1    1
dim(traces_detrended) <- dim(traces_detrended)[1:2]
dim(traces_detrended)
#> [1] 4045   85
```

It is good info that your _intention is to detrend every column separately_ and that _some of them show a stronger decay than others (they also have different base mean fluorescence)_, this means that detrending with automatic parameter selection (e.g. `tau = "auto"`) is not applicable. I've used `tau = 100` above but you'll have to play around to see what works. It seems to me that `img_detrend_exp()` is probbably what you want, but that's just a hunch.

**Comment by hummuscience** [comment]
Thank you for this! I will give it a try.

Detrending the whole image (before ROI extraction) might also be a solution but I doubt this will work well with R since each video is >5Gb in size. (1024 by 1024 with 12k frames is my typical video)

What is your experience with such videos?

**Comment by rorynolan** [comment]
I think that should be fine. The automatic parameter finding e.g. `tau = "auto"` will probably be very slow in this case but it will happen. I would try chopping it (e.g to 256x256x1k) and see if that works, then scale from there. Make sure you have plenty of memory though, you often need upwards of 4x your data size. 

If you want to send me the image (e.g. by dropbox link) I can have a go and let you know how it goes for me.
