### ISSUE TITLE
test results appear to depend on number of RcppParallel threads used

### ISSUE THREAD

**Issue by kevinushey** [rorynolan/detrendr#5]
If I modify this function:

https://github.com/rorynolan/detrendr/blob/master/R/utils.R#L1-L14

to always use two threads (ie: just `return(2)` instead), then I see some test failures. For example:

```
x |  96 1     | best_params [48.9 s]
────────────────────────────────────────────────────────────────────────────────
test-best_params.R:101: failure: best_degree works
`d1` not equal to `d2`.
2/2 mismatches (average diff: 2)
[1] 22 - 20 ==  2
[2] 16 - 18 == -2
────────────────────────────────────────────────────────────────────────────────
```

and

```
x |  13 1     | dir-detrend [9.2 s]
────────────────────────────────────────────────────────────────────────────────
test-dir-detrend.R:166: failure: detrending entire derectories works
unlist(detrendeds) not equal to unlist(detrendeds_dir).
2/375900 mismatches (average diff: 1)
[756] 1 - 0 ==  1
[759] 0 - 1 == -1
────────────────────────────────────────────────────────────────────────────────
```

Is it expected that test results could be sensitive to the number of threads used?

```
> utils::sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  parallel  methods  
[8] base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     packrat_0.5.0-25 digest_0.6.25    backports_1.1.7 
 [5] magrittr_1.5     evaluate_0.14    stringi_1.4.6    rlang_0.4.6     
 [9] checkmate_2.0.0  rmarkdown_2.3    tools_3.6.3      stringr_1.4.0   
[13] glue_1.4.1       purrr_0.3.4      ijtiff_2.0.5     xfun_0.15       
[17] yaml_2.2.1       abind_1.4-5      compiler_3.6.3   htmltools_0.4.0 
[21] knitr_1.29  
```

**Comment by kevinushey** [comment]
Disclaimer: I'm the maintainer of the RcppParallel package, and due to segfaults with the latest version of GCC I'm planning on submitting a version of RcppParallel to ensure thread options can only be set once per session. Unfortunately, with this change, this package fails in reverse dependency checks and so I've thus far been unable to submit to CRAN.

**Comment by rorynolan** [comment]
This is expected. Within this package I use the C++ stdlib RNG for bernoulli random numbers and indeed with my implementation the result is constant for a given seed and constant number of cores.
I think the best thing is for me to `skip_on_cran()` these tests and then wait for the new RcppParallel and unskip and amend. That way they won't bother you with the revdep. I'll do that in the next few hours.

**Comment by rorynolan** [comment]
Submitted now. Should be on CRAN within a day.

**Comment by kevinushey** [comment]
Awesome! Thank you very much for the quick response + submission.

**Comment by rorynolan** [comment]
No problem at all. Keep up the good work on RcppParallel and all your projects, great work!
