### ISSUE TITLE
long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537

### ISSUE THREAD

**Issue by cb12ag** [rorynolan/detrendr#7]
dim(my_img)
    [1] 1024 1024 1 6338

    display( detrendr::mean_pillars( autothresholdr::mean_stack_thresh(my_img[, , 1, ], "h") ) )
    Error in checkmate::assert_numeric(img, lower = 0) :
    long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537

    plot_tbl <- tibble(
    frame = seq_len(dim(my_img)[4]),
    channel1 = apply(autothresholdr::mean_stack_thresh(my_img[, , 1, ], "h"), 4,
    mean, na.rm = TRUE)
    ) %>% gather(ch, mean, -frame)
    Error in checkmate::assert_numeric(img, lower = 0) :
    long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537

**Comment by rorynolan** [comment]
This stems from a problem in the `checkmate` package. I have submitted a pull request containing a fix there https://github.com/mllg/checkmate/pull/231. It has been accepted but not yet put on CRAN, so until then, you could do `remotes::install_github("mllg/checkmate")` to get my patched `checkmate`. Please try that and tell me how it goes.
